In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np
# from sklearn.cluster import KMeans
# from sklearn import metrics
# from sklearn import datasets, ensemble
# from sklearn.inspection import permutation_importance
# from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
# xgboost.__version__

In [3]:
pd. show_versions()


INSTALLED VERSIONS
------------------
commit           : 7d32926db8f7541c356066dcadabf854487738de
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_India.1252

pandas           : 1.2.2
numpy            : 1.19.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.22
pytest           : 6.2.2
hypothesis       : None
sphinx           : 3.5.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3

In [4]:
df=pd.read_csv("Data.csv")

In [5]:
df.head()

applicant_id  years_of_insurance_with_us  regular_checkup_lasy_year  \
0          5000                           3                          1   
1          5001                           0                          0   
2          5002                           1                          0   
3          5003                           7                          4   
4          5004                           3                          1   

   adventure_sports Occupation  visited_doctor_last_1_year cholesterol_level  \
0                 1    Salried                           2        125 to 150   
1                 0    Student                           4        150 to 175   
2                 0   Business                           4        200 to 225   
3                 0   Business                           2        175 to 200   
4                 0    Student                           2        150 to 175   

   daily_avg_steps  age  heart_decs_history  ...   smoking_status  \
0             4866   28                   1  ...          Unknown   
1             6411   50                   0  ...  formerly smoked   
2             4509   68                   0  ...  formerly smoked   
3             6214   51                   0  ...          Unknown   
4             4938   44                   0  ...     never smoked   

  Year_last_admitted   Location  weight covered_by_any_other_company  Alcohol  \
0                NaN    Chennai      67                            N     Rare   
1                NaN     Jaipur      58                            N     Rare   
2                NaN     Jaipur      73                            N    Daily   
3                NaN    Chennai      71                            Y     Rare   
4             2004.0  Bangalore      74                            N       No   

   exercise  weight_change_in_last_one_year fat_percentage insurance_cost  
0  Moderate                               1             25          20978  
1  Moderate                               3             27           6170  
2   Extreme                               0             32          28382  
3        No                               3             37          27148  
4   Extreme                               0             34          29616  

[5 rows x 24 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   applicant_id                    25000 non-null  int64  
 1   years_of_insurance_with_us      25000 non-null  int64  
 2   regular_checkup_lasy_year       25000 non-null  int64  
 3   adventure_sports                25000 non-null  int64  
 4   Occupation                      25000 non-null  object 
 5   visited_doctor_last_1_year      25000 non-null  int64  
 6   cholesterol_level               25000 non-null  object 
 7   daily_avg_steps                 25000 non-null  int64  
 8   age                             25000 non-null  int64  
 9   heart_decs_history              25000 non-null  int64  
 10  other_major_decs_history        25000 non-null  int64  
 11  Gender                          25000 non-null  object 
 12  avg_glucose_level               

In [7]:
df['years_of_insurance_with_us']=df['years_of_insurance_with_us'].astype('object')
df['adventure_sports']=df['adventure_sports'].astype('object')
df['visited_doctor_last_1_year']=df['visited_doctor_last_1_year'].astype('object')
df['heart_decs_history']=df['heart_decs_history'].astype('object')
df['other_major_decs_history']=df['other_major_decs_history'].astype('object')
df['Year_last_admitted']=df['Year_last_admitted'].astype('object')
df['other_major_decs_history']=df['other_major_decs_history'].astype('object')
df['other_major_decs_history']=df['other_major_decs_history'].astype('object')
df['other_major_decs_history']=df['other_major_decs_history'].astype('object')
df['regular_checkup_lasy_year']=df['regular_checkup_lasy_year'].astype('object')

In [8]:
df.dropna(subset=['Year_last_admitted'], inplace=True)

In [9]:
df_median=df['bmi'].median()

In [10]:
df=df.fillna(value=df_median)

In [11]:
df=df.replace('Unknown', np.nan)

In [12]:
df = df[df['smoking_status'].notna()]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9063 entries, 4 to 24999
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   applicant_id                    9063 non-null   int64  
 1   years_of_insurance_with_us      9063 non-null   int64  
 2   regular_checkup_lasy_year       9063 non-null   int64  
 3   adventure_sports                9063 non-null   int64  
 4   Occupation                      9063 non-null   object 
 5   visited_doctor_last_1_year      9063 non-null   int64  
 6   cholesterol_level               9063 non-null   object 
 7   daily_avg_steps                 9063 non-null   int64  
 8   age                             9063 non-null   int64  
 9   heart_decs_history              9063 non-null   int64  
 10  other_major_decs_history        9063 non-null   int64  
 11  Gender                          9063 non-null   object 
 12  avg_glucose_level               9

In [14]:
for feature in df.columns: 
    if df[feature].dtype == 'object': 
        print('\n')
        print('feature:',feature)
        print(pd.Categorical(df[feature].unique()))
        print(pd.Categorical(df[feature].unique()).codes)
        df[feature] = pd.Categorical(df[feature]).codes



feature: Occupation
['Student', 'Salried', 'Business']
Categories (3, object): ['Business', 'Salried', 'Student']
[2 1 0]


feature: cholesterol_level
['150 to 175', '125 to 150', '200 to 225', '175 to 200', '225 to 250']
Categories (5, object): ['125 to 150', '150 to 175', '175 to 200', '200 to 225', '225 to 250']
[1 0 3 2 4]


feature: Gender
['Male', 'Female']
Categories (2, object): ['Female', 'Male']
[1 0]


feature: smoking_status
['never smoked', 'smokes', 'formerly smoked']
Categories (3, object): ['formerly smoked', 'never smoked', 'smokes']
[1 2 0]


feature: Location
['Bangalore', 'Guwahati', 'Mumbai', 'Surat', 'Mangalore', ..., 'Chennai', 'Delhi', 'Bhubaneswar', 'Kanpur', 'Lucknow']
Length: 15
Categories (15, object): ['Ahmedabad', 'Bangalore', 'Bhubaneswar', 'Chennai', ..., 'Mumbai', 'Nagpur', 'Pune', 'Surat']
[ 1  5 11 14 10 13  6  8 12  0  3  4  2  7  9]


feature: covered_by_any_other_company
['N', 'Y']
Categories (2, object): ['N', 'Y']
[0 1]


feature: Alcohol
['No'

In [15]:
# df = pd.get_dummies(df, columns=['Occupation','Gender','smoking_status','covered_by_any_other_company','Alcohol','exercise'])

In [16]:
df.head()

applicant_id  years_of_insurance_with_us  regular_checkup_lasy_year  \
4           5004                           3                          1   
6           5006                           8                          0   
8           5008                           8                          1   
10          5010                           7                          1   
13          5013                           6                          1   

    adventure_sports  Occupation  visited_doctor_last_1_year  \
4                  0           2                           2   
6                  0           2                           4   
8                  0           1                           4   
10                 0           2                           3   
13                 0           0                           2   

    cholesterol_level  daily_avg_steps  age  heart_decs_history  ...  \
4                   1             4938   44                   0  ...   
6                   0             4676   40                   0  ...   
8                   0             5632   45                   0  ...   
10                  0             4829   35                   0  ...   
13                  1             7089   30                   0  ...   

    smoking_status  Year_last_admitted  Location  weight  \
4                1              2004.0         1      74   
6                1              2004.0         5      81   
8                2              2007.0        11      67   
10               0              1994.0         1      74   
13               0              2002.0        14      75   

    covered_by_any_other_company  Alcohol  exercise  \
4                              0        1         0   
6                              0        1         1   
8                              1        2         2   
10                             0        2         0   
13                             1        2         1   

    weight_change_in_last_one_year  fat_percentage  insurance_cost  
4                                0              34           29616  
6                                3              16           37020  
8                                1              12           22212  
10                               2              16           25914  
13                               1              21           37020  

[5 rows x 24 columns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9063 entries, 4 to 24999
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   applicant_id                    9063 non-null   int64  
 1   years_of_insurance_with_us      9063 non-null   int64  
 2   regular_checkup_lasy_year       9063 non-null   int64  
 3   adventure_sports                9063 non-null   int64  
 4   Occupation                      9063 non-null   int8   
 5   visited_doctor_last_1_year      9063 non-null   int64  
 6   cholesterol_level               9063 non-null   int8   
 7   daily_avg_steps                 9063 non-null   int64  
 8   age                             9063 non-null   int64  
 9   heart_decs_history              9063 non-null   int64  
 10  other_major_decs_history        9063 non-null   int64  
 11  Gender                          9063 non-null   int8   
 12  avg_glucose_level               9

In [18]:
# df['cholesterol_level']=np.where(df['cholesterol_level'] =='125 to 150', 'good', df['cholesterol_level'])
# df['cholesterol_level']=np.where(df['cholesterol_level'] =='150 to 175', 'acceptable', df['cholesterol_level'])
# df['cholesterol_level']=np.where(df['cholesterol_level'] =='175 to 200', 'acceptable', df['cholesterol_level'])
# df['cholesterol_level']=np.where(df['cholesterol_level'] =='200 to 225', 'borderline', df['cholesterol_level'])
# df['cholesterol_level']=np.where(df['cholesterol_level'] =='225 to 250', 'risk', df['cholesterol_level'])

In [19]:
# df = pd.get_dummies(df, columns=['cholesterol_level'])

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9063 entries, 4 to 24999
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   applicant_id                    9063 non-null   int64  
 1   years_of_insurance_with_us      9063 non-null   int64  
 2   regular_checkup_lasy_year       9063 non-null   int64  
 3   adventure_sports                9063 non-null   int64  
 4   Occupation                      9063 non-null   int8   
 5   visited_doctor_last_1_year      9063 non-null   int64  
 6   cholesterol_level               9063 non-null   int8   
 7   daily_avg_steps                 9063 non-null   int64  
 8   age                             9063 non-null   int64  
 9   heart_decs_history              9063 non-null   int64  
 10  other_major_decs_history        9063 non-null   int64  
 11  Gender                          9063 non-null   int8   
 12  avg_glucose_level               9

In [21]:
df=df.drop(['Location'], axis=1)

In [22]:
df=df.drop(['applicant_id'], axis=1)

In [23]:
df=df.drop(['Year_last_admitted'], axis=1)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9063 entries, 4 to 24999
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   years_of_insurance_with_us      9063 non-null   int64  
 1   regular_checkup_lasy_year       9063 non-null   int64  
 2   adventure_sports                9063 non-null   int64  
 3   Occupation                      9063 non-null   int8   
 4   visited_doctor_last_1_year      9063 non-null   int64  
 5   cholesterol_level               9063 non-null   int8   
 6   daily_avg_steps                 9063 non-null   int64  
 7   age                             9063 non-null   int64  
 8   heart_decs_history              9063 non-null   int64  
 9   other_major_decs_history        9063 non-null   int64  
 10  Gender                          9063 non-null   int8   
 11  avg_glucose_level               9063 non-null   int64  
 12  bmi                             9

In [25]:
# Copy all the predictor variables into X dataframe
X1 = df.drop('insurance_cost', axis=1)

# Copy target into the y dataframe. 
y1 = df[['insurance_cost']]

In [26]:
# Split X and y into training and test set in 70:30 ratio
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.3 , random_state=1)

In [27]:
# !pip install xgboost
import xgboost
regressor=xgboost.XGBRegressor()

In [28]:
regressor.fit(X_train1,y_train1)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=12,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [29]:
#R square of training data
regressor.score(X_train1,y_train1)

0.9885036182067429

In [30]:
#R square of testing data
regressor.score(X_test1,y_test1)

0.9454263048231195

In [31]:
import pickle

In [33]:
# save the model to disk
pickle_out = open("testModel.pkl","wb")
pickle.dump(regressor, pickle_out)
loaded_model = pickle.load(open("testModel.pkl", "rb")) 
result = loaded_model.score(X_test1, y_test1) 
print(result)

0.9454263048231195
